// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyfjbveygjvcvrdvggvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5ZmpidmV5Z2p2Y3ZyZHZnZ3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MzQ5MTksImV4cCI6MjA1MTQxMDkxOX0._Y2U2or4z4la8gxj8rqNBTcHXNPnKnxwsMEtikGPUqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);