// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqvhtqapgovmlthsovlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdmh0cWFwZ292bWx0aHNvdmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mjk1MTUsImV4cCI6MjA2NDIwNTUxNX0.bWjJbeN3uwvl3qrU_jN4Ica9LSrQMALjiPwWpJDtedU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);